n_cv: 5
n_jobs: 5
metrics: f1
n_estimators: 100
param_grid: 
    max_depth:
        - 1
        - 2
        - 4
        - 8
        - 16
    min_samples_leaf:
        - 1
        - 0.01
        - 0.1
        - 0.2
    min_impurity_decrease:
        - 0
        - 0.000001
        - 0.0001
        - 0.01
random_state: 43